---
# Das Default Profil wenn der Server Standalone läuft
spring:
  profiles: default
  application:
    name: tpm-eureka-server
server:
  port: 8761
eureka:
  instance:
    hostname: eurekahost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      #defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      defaultZone: http://tpm-eureka-server.local.pcfdev.io/
