spring:
  profiles: default
  application:
    name: tpm-people-client
eureka:
  client:
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8010/eureka/,http://localhost:8011/eureka/,http://localhost:8012/eureka/,http://localhost:8013/eureka/
server:
  port: ${PORT:${SERVER_PORT:0}}   # beliebiger Port
