spring:
  profiles: default
  application:
    name: tpm-people-server
  datasource:
    url: jdbc:mysql://localhost:3306/06-complete
    username: root
    password:
    driver-class-name: com.mysql.jdbc.Driver
eureka:
  client:
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      #defaultZone: http://tpm-eureka-server.local.pcfdev.io/
server:
  port: ${PORT:${SERVER_PORT:0}}   # beliebiger Port
logging.level.org.hibernate.sql: DEBUG
logging.level.org.flyway: DEBUG
