---
# Das Default Profil wenn der Server Standalone läuft
spring:
  profiles: default
server:
  port: 8010
eureka:
  instance:
    hostname: eurekahost
  client:
    registerWithEureka: true
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  application:
    name: tpm-eureka-server
