spring:
  profiles: default
  application:
    name: tpm-people-client
eureka:
  client:
    fetchRegistry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8010/eureka
server:
  port: ${PORT:${SERVER_PORT:0}}   # beliebiger Port
