---
spring:
  profiles: default
  application:
    name: tpm-admin
eureka:
  client:
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8080
